version: '3.7'

services:
  templid-tools:
    tty: true
    container_name: templid-tools
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    networks:
      - templid-tools-network
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 8080:8080

networks:
  templid-tools-network:
